name: CI
on: 
  push: 
    branches: [ master ]
  pull_request: 
     branches: [ master ]
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html
          
  unit-tests:
    needs: [lint]
    runs-on : ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  ui-tests:
    needs: [unit-tests]
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run Ui Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: ui_test_report
          path: app/build/reports/androidTests/connected/

